# Generated by Django 4.2.8 on 2023-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
    ]
