# Generated by Django 4.2.8 on 2023-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogcomments_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='image',
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='email',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='username',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
