# Generated by Django 3.1 on 2023-12-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageDesign', '0003_auto_20231207_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to='')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='text',
            field=models.TextField(max_length=700),
        ),
    ]
