# Generated by Django 3.1 on 2023-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageDesign', '0004_auto_20231207_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(default=1, max_length=1000, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='header',
            field=models.CharField(max_length=200),
        ),
    ]
