# Generated by Django 3.1 on 2023-12-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageDesign', '0005_auto_20231207_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subHeader', models.CharField(max_length=1000)),
                ('header', models.CharField(max_length=1000)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
