# Generated by Django 4.2.8 on 2023-12-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageDesign', '0009_alter_aboutcontent_id_alter_abouttextcontent_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComments',
        ),
    ]
